site_name: Shichao's Notes
site_description: Shichao's Notes
site_url: https://notes.shichao.io
repo_url: https://github.com/shichao-an/notes
theme: flatly
pages:
    - Home: 'index.md'
    - APUE:
        - 'Chapter 1. UNIX System Overview': 'apue/ch1.md'
        - 'Chapter 2. UNIX Standardization and Implementations': 'apue/ch2.md'
        - 'Chapter 3. File I/O': 'apue/ch3.md'
        - 'Chapter 4. Files and Directories': 'apue/ch4.md'
        - 'Chapter 5. Standard I/O Library': 'apue/ch5.md'
        - 'Chapter 6. System Data Files and Information': 'apue/ch6.md'
        - 'Chapter 7. Process Environment': 'apue/ch7.md'
        - 'Chapter 8. Process Control': 'apue/ch8.md'
    - UTLK:
        - 'Chapter 1. Introduction': 'utlk/ch1.md'
        - 'Chapter 2. Memory Addressing': 'utlk/ch2.md'
    - UNP:
        - 'Chapter 1. Introduction': 'unp/ch1.md'
        - 'Chapter 2. The Transport Layer: TCP, UDP, and SCTP': 'unp/ch2.md'
        - 'Chapter 3. Sockets Introduction': 'unp/ch3.md'
    - ICND:
        - 'ICND1 Part I: Networking Fundamentals': 'icnd1/part1.md'
        - 'ICND2 Part I: LAN Switching': 'icnd2/part1.md'
    - TCPv1:
        - 'Chapter 1. Introduction': 'tcpv1/ch1.md'
        - 'Chapter 2. The Internet Address Architecture': 'tcpv1/ch2.md'
        - 'Chapter 10. User Datagram Protocol (UDP) and IP Fragmentation': 'tcpv1/ch10.md'
        - 'Headers': 'tcpv1/headers.md'
    - Others:
        - 'HTAE': 'htae/index.md'
        - 'Go': 'golang/index.md'
        - 'Bash': 'bash/index.md'
        - 'C': 'c/index.md'
        - 'iptables': 'iptables/index.md'
        - 'Nginx': 'nginx/index.md'
        - 'Vim': 'vim/index.md'
